[package]
name = "server"
version = "0.1.0"
authors = ["Venkatesh-Prasad Ranganath <venkateshprasad.ranganath@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "0.2"
actix-web = "1.0.0"
rand = "0.6.5"
serde_json = "1.0.39"
serde_urlencoded = "0.5.5"
