all:
  children:
    all_raspi:
      hosts:
        192.168.2.[10:15]:
      vars:
        ansible_shell_executable: /bin/bash
    master_raspi:
      hosts:
        192.168.2.10:
      vars:
        ansible_shell_executable: /bin/bash
    worker_raspis:
      hosts:
        192.168.2.[11:15]:
      vars:
        ansible_shell_executable: /bin/bash
