all:
  children:
    all_raspi:
      hosts:
        192.168.2.[10:15]:
      vars:
        ansible_shell_executable: /bin/bash
    subject_raspi:
      hosts:
        192.168.2.[10:14]:
      vars:
        ansible_shell_executable: /bin/bash
